name: 'Salesforce CLI Setup Helper'
author: sopra-steria-salesforce
description: 'This action allows to use Salesforce SF CLI from GitHub Actions'

branding:
  icon: 'terminal'
  color: 'purple'

inputs:
  sf-cli-version:
    description: sf cli version number. Specify a version number (x.x.x) or empty for the latest version
    required: false
  auth-url:
    description: The auth-url to be used in the auth-url authentication flow
    required: false
  username:
    description: The username to be used in the jwt authentication flow
    required: false
  client-id:
    description: The client id to be used in the jwt authentication flow
    required: false
  private-key:
    description: The private key to be used in the jwt authentication flow
    required: false
  private-key-base64:
    description: The base64 encoded private key to be used in the jwt authentication flow
    required: false
  access-token:
    description: The access token to be used in the access-token flow
    required: false
  instance-url:
    description: The instance url be used in the access-token flow
    required: false

runs:
  using: node20
  main: dist/index.js
